package com.newoether.agora.api.util

import com.newoether.agora.model.ChatMessage
import com.newoether.agora.model.Participant
import com.newoether.agora.util.Constants

/**
 * Full message preparation pipeline: context window truncation, consecutive
 * same-role merge, empty-turn stripping, then tool message validation. All providers MUST
 * call this before converting messages to their API format.
 */
fun prepareMessages(messages: List<ChatMessage>, maxUserMessages: Int): List<ChatMessage> {
    return validateToolMessages(
        stripEmptyTurns(mergeConsecutiveSameRole(limitContext(messages, maxUserMessages)))
    )
}

/**
 * Drops turns that would serialize to an empty/whitespace-only content block.
 *
 * Anthropic hard-rejects those with `400 messages: text content blocks must contain
 * non-whitespace text`, and other providers silently degrade on them. Such turns are
 * routine in practice: a generation stopped before its first token, an interrupted turn
 * that emitted only a newline, or two blank messages merged with "\n".
 *
 * A turn survives if it carries anything else of substance — images, or tool protocol
 * payload (tool_/result_ rows, whose content lives in segments/toolCall, not text).
 * Runs AFTER the merge so a blank fragment absorbed into a non-blank neighbor is kept.
 */
fun stripEmptyTurns(messages: List<ChatMessage>): List<ChatMessage> =
    messages.filter { msg ->
        msg.text.isNotBlank() ||
            msg.images.isNotEmpty() ||
            msg.isToolProtocolMessage() ||
            msg.toolCall != null ||
            msg.segments?.any { it.type == "tool" } == true
    }

/**
 * Builds an API-only view where assistant-generated images remain available for
 * visual follow-ups without being serialized as assistant-side image content.
 *
 * Chat completion schemas treat images as user inputs. Agora stores generated
 * images on model messages for display, so the latest generated image set is
 * projected onto the latest normal user message when images are being sent.
 */
fun projectAssistantImagesToLatestUserMessage(
    messages: List<ChatMessage>,
    includeImages: Boolean
): List<ChatMessage> {
    if (messages.isEmpty()) return messages

    val latestUserIndex = messages.indexOfLast { it.isNormalUserMessage() }
    val generatedImages = if (includeImages && latestUserIndex >= 0) {
        messages
            .asSequence()
            .take(latestUserIndex)
            .filter { it.isNormalAssistantMessage() && it.images.isNotEmpty() }
            .lastOrNull()
            ?.images
            ?.filter { it.isNotBlank() }
            .orEmpty()
    } else {
        emptyList()
    }

    var changed = false
    val projected = messages.mapIndexed { index, msg ->
        var next = msg
        if (msg.isNormalAssistantMessage() && msg.images.isNotEmpty()) {
            next = next.copy(images = emptyList())
            changed = true
        }
        if (index == latestUserIndex && generatedImages.isNotEmpty()) {
            next = next.copy(
                text = addGeneratedImageContextNote(next.text, generatedImages.size),
                images = (generatedImages + next.images).distinct()
            )
            changed = true
        }
        next
    }

    return if (changed) projected else messages
}

private fun ChatMessage.isNormalUserMessage(): Boolean =
    participant == Participant.USER && !isToolProtocolMessage()

private fun ChatMessage.isNormalAssistantMessage(): Boolean =
    participant == Participant.MODEL && !isToolProtocolMessage()

internal fun ChatMessage.isToolProtocolMessage(): Boolean =
    id.startsWith(Constants.TOOL_MSG_PREFIX) || id.startsWith(Constants.RESULT_MSG_PREFIX)

private fun addGeneratedImageContextNote(text: String, imageCount: Int): String {
    val note = if (imageCount == 1) {
        "[Visual context: the first attached image was generated by the assistant earlier in this conversation.]"
    } else {
        "[Visual context: the first $imageCount attached images were generated by the assistant earlier in this conversation.]"
    }
    return if (text.isBlank()) note else "$note\n\n$text"
}

/**
 * Merges consecutive non-tool messages that share the same participant.
 * This handles orphans left by message deletion (e.g. two user messages
 * in a row after removing an assistant reply) and keeps the message list
 * compliant with providers that require strict role alternation.
 *
 * Tool messages (tool_/result_) pass through unchanged — they are validated
 * separately by [validateToolMessages].
 */
fun mergeConsecutiveSameRole(messages: List<ChatMessage>): List<ChatMessage> {
    if (messages.isEmpty()) return messages
    val result = mutableListOf<ChatMessage>()
    var i = 0
    while (i < messages.size) {
        val current = messages[i]
        val isTool = current.id.startsWith(Constants.TOOL_MSG_PREFIX) ||
            current.id.startsWith(Constants.RESULT_MSG_PREFIX)
        if (isTool) {
            result.add(current)
            i++
            continue
        }
        // Find consecutive messages with the same participant
        var j = i + 1
        while (j < messages.size) {
            val next = messages[j]
            val nextIsTool = next.id.startsWith(Constants.TOOL_MSG_PREFIX) ||
                next.id.startsWith(Constants.RESULT_MSG_PREFIX)
            if (nextIsTool || next.participant != current.participant) break
            j++
        }
        if (j == i + 1) {
            // No merge needed
            result.add(current)
        } else {
            // Merge messages[i..j-1] into one
            val merged = messages.subList(i, j)
            val mergedText = merged.joinToString("\n") { it.text }
            val mergedImages = merged.flatMap { it.images }
            result.add(current.copy(text = mergedText, images = mergedImages))
        }
        i = j
    }
    return result
}

/**
 * Validates tool_ / result_ message pairing and fixes ID mismatches.
 *
 * Rules enforced:
 *  - Every tool_ message must be immediately followed by >= 1 result_ message
 *  - Every result_ message must be immediately preceded by a tool_ message
 *  - Each result_ segment's toolCallId matches the corresponding tool_use segment
 *
 * Orphaned tool_ and result_ messages are dropped. All non-tool messages
 * pass through unchanged.
 */
fun validateToolMessages(messages: List<ChatMessage>): List<ChatMessage> {
    val result = mutableListOf<ChatMessage>()
    var i = 0
    while (i < messages.size) {
        val msg = messages[i]
        when {
            msg.id.startsWith(Constants.TOOL_MSG_PREFIX) -> {
                val resultMessages = mutableListOf<ChatMessage>()
                var j = i + 1
                while (j < messages.size && messages[j].id.startsWith(Constants.RESULT_MSG_PREFIX)) {
                    resultMessages.add(messages[j])
                    j++
                }
                if (resultMessages.isNotEmpty()) {
                    result.add(msg)
                    result.addAll(fixToolIds(msg, resultMessages))
                    i = j
                } else {
                    i++ // orphan tool_ — drop
                }
            }
            msg.id.startsWith(Constants.RESULT_MSG_PREFIX) -> {
                i++ // orphan result_ — drop
            }
            else -> {
                result.add(msg)
                i++
            }
        }
    }
    return result
}

/**
 * Fixes toolCallId mismatches between a tool_ message's tool-use segments and
 * the following result_ messages. Match is by position: Nth result_ → Nth tool-use.
 * Result rows beyond the tool-use count are dropped — a tool_result pointing at a
 * nonexistent tool_use fails the whole request (Anthropic/OpenAI reject it with 400).
 */
private fun fixToolIds(
    toolMsg: ChatMessage,
    resultMessages: List<ChatMessage>
): List<ChatMessage> {
    val toolSegments = toolMsg.segments?.filter { it.type == "tool" } ?: return resultMessages
    if (toolSegments.isEmpty()) return resultMessages
    val useIds = toolSegments.mapNotNull { it.toolCallId }
    if (useIds.size != toolSegments.size) return resultMessages

    return resultMessages.take(useIds.size).mapIndexed { idx, resultMsg ->
        val correctId = useIds[idx]

        val fixedSegments = resultMsg.segments?.map { seg ->
            if (seg.type == "tool" && seg.toolCallId != correctId) seg.copy(toolCallId = correctId) else seg
        }
        val fixedToolCall = resultMsg.toolCall?.let { tc ->
            if (tc.toolCallId != correctId) tc.copy(toolCallId = correctId) else tc
        }
        if (fixedSegments != resultMsg.segments || fixedToolCall != resultMsg.toolCall) {
            resultMsg.copy(segments = fixedSegments, toolCall = fixedToolCall)
        } else resultMsg
    }
}
